#!/bin/bash
# ehcp (Easy Hosting Control Panel) start/stop script
# www.ehcp.net



log="$2"
echo
echo

show_ehcp(){
	ps aux | grep ehcpdaemon2  | grep -v grep
	ps aux | grep "index.php daemon"  | grep -v grep
	ps aux | grep "ehcp_daemon.py" | grep -v grep
}


ehcp_start(){
	echo "Your OS info:"
	cat /etc/*ele*
	
	#Not used
	#echo "starting ehcp_daemon.py"
	#nohup /etc/init.d/ehcp_daemon.py >> /var/log/ehcp.log 2>&1 & 
	echo "starting ehcp.."
	
	cd /var/www/new/ehcp

	if [ -f path ] ; then # when running inside cron, we need default path. this path variable is filled when installing, in install.sh
		export PATH=`cat path`
	else
		echo "path file NOT FOUND, ehcp may not work correctly in crontab..."
	fi


	./ehcpdaemon.sh
	show_ehcp

	if [ "$log" == "log" ] ; then
		echo "log gosteriliyor"
		tail -f /var/log/ehcp.log
	fi
		

}

ehcp_stop(){
	echo "stopping ehcp.."
	echo "stopping ehcpdaemon2.sh"
	ps aux | grep ehcpdaemon2 | grep -v grep | awk '{print $2}' | xargs kill -9  > /dev/null 2>&1
	echo "stopping index.php daemon"
	ps aux | grep "index.php daemon" | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
	echo "stopping ehcp_daemon.py, python background server process"
	ps aux | grep ehcp_daemon.py | grep -v grep | awk '{print $2}' | xargs kill > /dev/null 2>&1
		
	show_ehcp
}


case $1 in
	start)
		ehcp_start
	;;

	stop)
		ehcp_stop
	;;

	restart)
		ehcp_stop
		ehcp_start
	;;
	
	status)
		show_ehcp
	
	;;

	*)
		echo "Usage: /etc/init.d/ehcp {start|stop|restart|status}"
	;;
esac
